application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  # Value retrieved from Postmark's API docs
  base_url: "https://api.postmarkapp.com"
  # Use the single sender email you authorized on postmark!
  sender_email: "grbic.t@northeastern.edu"